import mysql.connector
from mysql.connector import Error

def connect_db():
    try:
        return mysql.connector.connect(
            host='localhost',
            user='root',         # Change to your username
            password='', # Change to your password
            database='college_db'
        )
    except Error as e:
        print(f"Connection Error: {e}")
        return None

def run_application():
    conn = connect_db()
    if not conn:
        return
    
    cursor = conn.cursor()

    while True:
        print("\n--- MYSQL PYTHON INTERFACE ---")
        print("1. Run TotalMarks Procedure (OUT Param)")
        print("2. Run Birthmonthdate Procedure (Cursor/Select)")
        print("3. Run MaxMinAge Procedure (Multiple OUT)")
        print("4. Add Student (Triggers Insert Log)")
        print("5. View Student Logs (Trigger Output)")
        print("6. Exit")
        
        choice = input("\nSelect an option: ")

        # --- PROCEDURE 1: TotalMarks ---
        if choice == '1':
            # Passing list [0] for OUT param1
            results = cursor.callproc('TotalMarks', [0])
            print(f"Result: Total Marks of all students = {results[0]}")

        # --- PROCEDURE 2: Birthmonthdate ---
        elif choice == '2':
            print("Checking for birthdays today...")
            cursor.callproc('Birthmonthdate')
            # Using stored_results because the procedure SELECTs inside a loop
            found = False
            for result in cursor.stored_results():
                for row in result.fetchall():
                    print(f"Birthday Boy/Girl: {row[1]} {row[2]} (ID: {row[0]})")
                    found = True
            if not found:
                print("No birthdays found for today.")

        # --- PROCEDURE 3: MaxMinAge ---
        elif choice == '3':
            # Passing [0, 0] for maxAge and minAge
            results = cursor.callproc('MaxMinAge', [0, 0])
            print(f"Age Stats -> Max: {results[0]}, Min: {results[1]}")

        # --- CRUD: INSERT (Triggers usually fire here) ---
        elif choice == '4':
            name = input("Enter Student Name: ")
            marks = int(input("Enter Marks: "))
            age = int(input("Enter Age: "))
            
            query = "INSERT INTO Student (name, marks, Age) VALUES (%s, %s, %s)"
            cursor.execute(query, (name, marks, age))
            conn.commit()
            print(f"Student {name} added! The database trigger has logged this action.")

        # --- CRUD: READ LOGS ---
        elif choice == '5':
            print("Reading logs generated by MySQL Triggers...")
            cursor.execute("SELECT * FROM stud_log ORDER BY log_time DESC")
            for log in cursor.fetchall():
                print(f"[{log[2]}] Action: {log[1]}")

        elif choice == '6':
            print("Closing connection. Bye bhai!")
            break
        
        else:
            print("Invalid choice!")

    cursor.close()
    conn.close()

if __name__ == "__main__":
    run_application()